Importing the Dependencies

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [4]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
237692,149352.0,-1.795969,1.171110,0.106506,-1.193818,0.248561,2.418984,-0.755729,1.774687,0.336809,...,0.319463,1.165454,-0.179041,-2.348549,-0.166829,0.827846,0.386992,0.141743,34.99,0.0
237693,149352.0,1.971373,0.563968,-1.052447,3.549534,1.014790,0.643579,0.172618,-0.063923,-0.982008,...,0.256246,0.872402,-0.067301,0.068836,0.352030,0.252338,-0.029553,-0.049665,10.59,0.0
237694,149352.0,2.087787,0.239585,-1.743892,0.369307,0.595164,-0.764449,0.260053,-0.292133,0.329707,...,-0.361893,-0.878506,0.307024,0.410547,-0.197957,0.177523,-0.055255,-0.029636,1.29,0.0
237695,149353.0,-7.629245,6.859757,-4.889222,-2.993155,-0.461859,-1.253808,0.666932,0.963512,5.100547,...,-0.770141,0.420174,0.086960,0.125147,1.043297,-0.071343,0.785015,-0.697357,1.46,0.0
237696,149353.0,1.993109,-0.288264,-1.451488,0.105528,0.326851,-0.129957,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237697 entries, 0 to 237696
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    237697 non-null  float64
 1   V1      237697 non-null  float64
 2   V2      237697 non-null  float64
 3   V3      237697 non-null  float64
 4   V4      237697 non-null  float64
 5   V5      237697 non-null  float64
 6   V6      237697 non-null  float64
 7   V7      237696 non-null  float64
 8   V8      237696 non-null  float64
 9   V9      237696 non-null  float64
 10  V10     237696 non-null  float64
 11  V11     237696 non-null  float64
 12  V12     237696 non-null  float64
 13  V13     237696 non-null  float64
 14  V14     237696 non-null  float64
 15  V15     237696 non-null  float64
 16  V16     237696 non-null  float64
 17  V17     237696 non-null  float64
 18  V18     237696 non-null  float64
 19  V19     237696 non-null  float64
 20  V20     237696 non-null  float64
 21  V21     237696 non-null  float64
 22  V22     237696 non-null  float64
 23  V23     237696 non-null  float64
 24  V24     237696 non-null  float64
 25  V25     237696 non-null  float64
 26  V26     237696 non-null  float64
 27  V27     237696 non-null  float64
 28  V28     237696 non-null  float64
 29  Amount  237696 non-null  float64
 30  Class   237696 non-null  float64
dtypes: float64(31)
memory usage: 56.2 MB

In [7]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [8]:
credit_card_data['Class'].value_counts()

Class
0.0    237264
1.0       432
Name: count, dtype: int64

In [9]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(237264, 31)
(432, 31)

In [11]:
legit.Amount.describe()

count    237264.000000
mean         91.106801
std         252.226251
min           0.000000
25%           6.020000
50%          23.500000
75%          79.990000
max       19656.530000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     432.000000
mean      124.144329
std       256.669465
min         0.000000
25%         1.000000
50%        10.495000
75%       106.130000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,81892.974526,-0.046706,-0.025464,0.156631,0.027897,-0.044717,0.027138,-0.009607,0.001087,0.006434,...,0.007002,-0.005647,-0.017465,-0.008384,0.000614,0.030145,0.002271,-0.000665,0.001310,91.106801
1.0,70098.629630,-5.204670,3.909139,-7.374041,4.659017,-3.620727,-1.368585,-6.090541,0.644120,-2.691729,...,0.377813,0.770236,0.007310,-0.053105,-0.084728,0.050441,0.040993,0.207975,0.062435,124.144329

In [14]:
legit_sample = legit.sample(n=492)

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
198517,132523.0,2.004220,-0.238680,-1.047738,0.330213,-0.258602,-0.896256,-0.056099,-0.063167,0.552158,...,-0.247524,-0.697332,0.367366,-0.032284,-0.416649,0.184569,-0.083155,-0.073844,1.29,0.0
9647,14447.0,-0.706683,0.451427,2.007951,-0.742366,0.195589,-0.493160,0.177413,0.006094,1.148016,...,0.087781,0.428066,-0.067632,0.099426,-0.400140,0.877100,0.012010,0.114313,15.95,0.0
25154,33525.0,-1.333949,-0.235120,2.248269,-1.596738,0.309330,-1.145042,-0.292874,-1.033785,-1.296136,...,0.735711,-0.237430,-0.179983,0.600396,0.179595,-0.519465,0.024744,-0.194183,4.95,0.0
126214,77959.0,1.038406,-0.710118,0.754975,0.619871,-1.092931,-0.052785,-0.582535,0.025471,-0.805245,...,-0.145510,-0.135700,-0.059288,0.049625,0.275007,-0.282605,0.064316,0.054767,125.00,0.0
25167,33526.0,1.179329,0.625190,0.978704,2.479606,-0.264551,-0.380991,0.012135,-0.109993,-0.759039,...,-0.084945,-0.231245,0.062574,0.392529,0.338942,-0.133697,0.012380,0.032435,0.77,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
235616,148468.0,0.218810,2.715855,-5.111658,6.310661,-0.848345,-0.882446,-2.902079,0.939162,-3.627698,...,1.083640,1.037324,0.062325,0.532490,-0.149145,0.639580,0.351568,-0.001817,0.76,1.0
235634,148476.0,-1.125092,3.682876,-6.556168,4.016731,-0.425571,-2.031210,-2.650137,1.131249,-2.946890,...,1.185580,1.348156,-0.053686,0.284122,-1.174469,-0.087832,0.718790,0.676216,0.76,1.0
235644,148479.0,-1.541678,3.846800,-7.604114,3.121459,-1.254924,-2.084875,-2.385027,1.471140,-2.530507,...,1.096405,1.064222,0.065370,0.257209,-0.693654,-0.335702,0.577052,0.398348,122.68,1.0
237107,149096.0,1.184891,3.152084,-6.134780,5.531252,1.733867,-1.816861,-0.916696,0.265568,-3.158014,...,0.124236,-0.823865,-0.079887,0.028828,0.389711,0.060171,0.485187,0.326552,0.00,1.0
237426,149236.0,-1.370976,-0.025465,-2.774907,2.650530,4.511309,-3.289344,-0.118841,-0.014279,-0.932773,...,-0.048061,-0.599350,0.072193,-0.600351,0.371331,-0.370951,0.011970,0.145895,1.00,1.0

In [18]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    432
Name: count, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,83879.434959,-0.045909,0.029381,0.102088,-0.003991,-0.106002,-0.023660,-0.029307,-0.05937,0.084651,...,0.005823,0.046733,-0.035256,0.017436,-0.025285,-0.006796,0.021158,0.011600,0.007293,91.889370
1.0,70098.629630,-5.204670,3.909139,-7.374041,4.659017,-3.620727,-1.368585,-6.090541,0.64412,-2.691729,...,0.377813,0.770236,0.007310,-0.053105,-0.084728,0.050441,0.040993,0.207975,0.062435,124.144329

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
198517  132523.0  2.004220 -0.238680 -1.047738  0.330213 -0.258602 -0.896256
9647     14447.0 -0.706683  0.451427  2.007951 -0.742366  0.195589 -0.493160
25154    33525.0 -1.333949 -0.235120  2.248269 -1.596738  0.309330 -1.145042
126214   77959.0  1.038406 -0.710118  0.754975  0.619871 -1.092931 -0.052785
25167    33526.0  1.179329  0.625190  0.978704  2.479606 -0.264551 -0.380991
...          ...       ...       ...       ...       ...       ...       ...
235616  148468.0  0.218810  2.715855 -5.111658  6.310661 -0.848345 -0.882446
235634  148476.0 -1.125092  3.682876 -6.556168  4.016731 -0.425571 -2.031210
235644  148479.0 -1.541678  3.846800 -7.604114  3.121459 -1.254924 -2.084875
237107  149096.0  1.184891  3.152084 -6.134780  5.531252  1.733867 -1.816861
237426  149236.0 -1.370976 -0.025465 -2.774907  2.650530  4.511309 -3.289344

              V7        V8        V9  ...       V20       V21       V22  \
198517 -0.056099 -0.063167  0.552158  ... -0.340809 -0.247524 -0.697332
9647    0.177413  0.006094  1.148016  ... -0.049298  0.087781  0.428066
25154  -0.292874 -1.033785 -1.296136  ... -0.174580  0.735711 -0.237430
126214 -0.582535  0.025471 -0.805245  ... -0.318181 -0.145510 -0.135700
25167   0.012135 -0.109993 -0.759039  ... -0.077952 -0.084945 -0.231245
...          ...       ...       ...  ...       ...       ...       ...
235616 -2.902079  0.939162 -3.627698  ...  0.381682  1.083640  1.037324
235634 -2.650137  1.131249 -2.946890  ...  0.452241  1.185580  1.348156
235644 -2.385027  1.471140 -2.530507  ...  0.114760  1.096405  1.064222
237107 -0.916696  0.265568 -3.158014  ...  0.336442  0.124236 -0.823865
237426 -0.118841 -0.014279 -0.932773  ...  0.701292 -0.048061 -0.599350

             V23       V24       V25       V26       V27       V28  Amount
198517  0.367366 -0.032284 -0.416649  0.184569 -0.083155 -0.073844    1.29
9647   -0.067632  0.099426 -0.400140  0.877100  0.012010  0.114313   15.95
25154  -0.179983  0.600396  0.179595 -0.519465  0.024744 -0.194183    4.95
126214 -0.059288  0.049625  0.275007 -0.282605  0.064316  0.054767  125.00
25167   0.062574  0.392529  0.338942 -0.133697  0.012380  0.032435    0.77
...          ...       ...       ...       ...       ...       ...     ...
235616  0.062325  0.532490 -0.149145  0.639580  0.351568 -0.001817    0.76
235634 -0.053686  0.284122 -1.174469 -0.087832  0.718790  0.676216    0.76
235644  0.065370  0.257209 -0.693654 -0.335702  0.577052  0.398348  122.68
237107 -0.079887  0.028828  0.389711  0.060171  0.485187  0.326552    0.00
237426  0.072193 -0.600351  0.371331 -0.370951  0.011970  0.145895    1.00

[924 rows x 30 columns]

In [22]:
print(Y)

198517    0.0
9647      0.0
25154     0.0
126214    0.0
25167     0.0
         ...
235616    1.0
235634    1.0
235644    1.0
237107    1.0
237426    1.0
Name: Class, Length: 924, dtype: float64

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(924, 30) (739, 30) (185, 30)

In [25]:
model = LogisticRegression()

In [26]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [28]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9580514208389715

In [29]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [30]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9513513513513514

In [31]:
import pickle

with open("credit_card_model.pkl", "wb") as file:

    pickle.dump(model, file)

print("Model exported")

Model exported